import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { Rightbar } from "@/components/Rightbar/Rightbar";
import { Player } from "@/components/Player";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wemsc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex justify-between">
          <Sidebar />
          <section className="bg-zinc-900 w-full h-full px-4 py-3 mb-28">
            <Header />
            {children}
          </section>
          <Rightbar />
        </main>
        <Player />
      </body>
    </html>
  );
}
