import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { Rightbar } from "@/components/Rightbar/Rightbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wemsc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " flex justify-between"}>
        <Sidebar />
        {children}
        <Rightbar />
      </body>
    </html>
  );
}
